### ISSUE TITLE
In order traversal makes no sense.

### ISSUE THREAD

**Issue by jonesmz** [parkershamblin/container-flow-chart#4]
That's not what std::vector is for. Though it supports it.

**Comment by parkershamblin** [comment]
@jonesmz I think this stackoverflow [comment](https://stackoverflow.com/questions/471432/in-which-scenario-do-i-use-a-particular-stl-container/22671607#comment67379115_22671607) and the Flow Chart creator's response to said comment [here[(https://stackoverflow.com/questions/471432/in-which-scenario-do-i-use-a-particular-stl-container/22671607#comment68871759_22671607) is relevant to this issue.

If you deem a change is necessary, I will update the Flow Chart according to your suggestions. Better yet, if you'd be willing to create a pull request with your suggested changes to the Flow Chart, I'd greatly appreciate it.

**Comment by parkershamblin** [comment]
@jonesmz Still looking for help on this. If you have the time to leave a response, it would really help me out.

**Comment by jonesmz** [comment]
How about changing "Keep sorted elements" to "Store sorted elements", to indicate that the things in the container are intended to be sorted items, and not items that are sorted by the container itself.

and then change

"In order traversals" to "Index based access", and "Lookup Keys" to "Key based access"

**Comment by parkershamblin** [comment]
https://stackoverflow.com/questions/471432/in-which-scenario-do-i-use-a-particular-stl-container/22671607#comment68871759_22671607
